# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RewardSciences
  class APIException < StandardError
    attr_reader :context, :response_code

    # The constructor.
    # @param [String] The reason for raising an exception
    # @param [HttpContext] The HttpContext of the API call.
    def initialize(reason, context)
      response = context.response
      super("#{ reason }: #{ exception_details(response) }")
      @context = context
      @response_code = response.status_code
    end

    private

    def exception_details(response)
      begin
        detail = JSON.parse(response.raw_body)['detail']
        detail.is_a?(Array) ? detail.to_sentence : detail
      rescue JSON::ParserError
        'Please contact support'
      end
    end
  end
end
