# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RewardSciences
  class BaseController
    attr_accessor :http_client, :http_call_back

    @@http_client = UnirestClient.new

    def initialize(http_client: nil, http_call_back: nil)
      @http_client = http_client ||= @@http_client
      @http_call_back = http_call_back
    end

    def validate_response(context)			
      if context.response.status_code == 400
        raise APIException.new "400 - Bad Request", context
      elsif context.response.status_code == 401
        raise APIException.new "401 - Unauthorized", context
      elsif context.response.status_code == 403
        raise APIException.new "403 - Forbidden", context
      elsif context.response.status_code == 404
        raise APIException.new "404 - Not Found", context
      elsif context.response.status_code == 415
        raise APIException.new "415 - Unsupported Media Type", context
      elsif context.response.status_code == 500
        raise APIException.new "500 - Server Error", context
      elsif !context.response.status_code.between?(200, 208) #[200,208] = HTTP OK
        raise APIException.new 'HTTP Response Not OK', context
      end
    end
  end
end