# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RewardSciences
  class Configuration
    class << self
      attr_accessor :base_uri
      attr_accessor :o_auth_access_token
    end
  end
end
