# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RewardSciences
  class RewardSciencesClient
    # Singleton access to rewards controller
    # @return [Rewards] Returns the controller instance
    def rewards
      Rewards.instance
    end

    # Singleton access to reward_categories controller
    # @return [RewardCategories] Returns the controller instance
    def reward_categories
      RewardCategories.instance
    end

    # Singleton access to users controller
    # @return [Users] Returns the controller instance
    def users
      Users.instance
    end

    # Singleton access to activities controller
    # @return [Activities] Returns the controller instance
    def activities
      Activities.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(o_auth_access_token, environment)
      domain = environment == 'production' ? 'rewardsciences.com' : 'rslsandbox.com'

      Configuration.o_auth_access_token = o_auth_access_token
      Configuration.base_uri = "https://api.#{ domain }"
    end
  end
end
